<?php require('template/header.phtml') ?>





    <?php
    if (isset($view->singular))
    {
        require_once('template/singleLot.phtml');

    }
    else
    {

        foreach ($view->lots as $lotData) {
            $title = $lotData->getItemtitle();
            $image = $lotData->getImageurl();
            $maxBid = $lotData->getCurrentMaxBid();
            $description = $lotData->getItemdescription();
            $id = $lotData->getLotsid();
            $url = "lots.php?idHolder=".$id."&select=select";



            echo "<div class ='container' id='content'>
            <div class ='row' >
                <div class=' col-lg-3 col-md-4 col-sm-6 col-xs-12'>"
                . "<a href=".$url."><h3>" . $title . "</h3></a>
                " . "<img id='lotsImage' src=" . $image . "> </div>" .



                "<div class=' col-lg-6 col-md-6 col-sm-6  ' ><p class='text-truncate'>" . $description . "</p>" .
                "<h3>current bid</h3>" .
                "<h3> £" . $maxBid . "</h3></div>".


                "</div></div>";
        }

    }

    ?>

<?php require('template/footer.phtml') ?>


